patch/Python/Setup.embedded

Hashlib has a c file it uses to query openssl for the hash functions it provides.  Since this file was missing from the embedded module spec, hashlib only had a few basic hash functions.
This enables things like rimpemd160, etc that come from openssl.
Thanks in advance!

Fix for missing hash functions from hashlib

---

Makefile

When configuring the iOS/watchOS/tvOS Python, the PATH is prepended
such that the (host) macOS Python x86_64 binary can be found. But the
`$(PROJECT_DIR)/build/macOS/python/bin` is not there yet. It is created
only later in the target
`dist/Python-$(PYTHON_VER)-$1-support.b$(BUILD_NUMBER).tar.gz`.
Until then, the macOS Python is only available in the
`$(PROJECT_DIR)/$(PYTHON_DIR-macOS)/dist/` dir. Therefore, this is the
correct dir to be used in the PATH var. At least I do assume this to be the case.
I think (but have not checked) this could apply to the other version branches, too.
Note: I noticed this by using the 3.6 branch and I don't have a python3.6 on PATH on my system. If you indeed have some python3.6 on your PATH, then you won't notice and silently that external python3.6 will …

Use correct PATH to find macOS Python in Makefile

---

Makefile

Hi.
Spaces in $(PATH) entries seems like a bad idea, but unfortunately VMWare Fusion automatically adds the following to $(PATH): /Applications/VMware Fusion.app/Contents/Public
This is causing your Makefile to die when it appends to $PATH before building python.  Adding quotes around the whole thing keeps it behaving itself for me.

added quotes when setting PATH so as to not choke on paths with spaces

---

patch/Python/Setup.macOS

This is a second try at #109, this time by including the curses modules in the static build instead of relying on the .so files in lib-dynload. Note that they are only included in macOS builds where the curses library is provided by the OS. Including curses modules on other platforms would not make such sense.

Include curses modules in macOS build

---

Makefile

Without this change, `make iOS` and similar will fail when there's a space in PATH:
```
cd build/iOS/libffi-3.4.2 && PATH=/Users/ambv/Dropbox/Python/Python-Apple-support/build/macOS/Python-3.11.0b1-macOS/_install/bin:/Users/ambv/.pyenv/shims:/Users/ambv/Library/Application Support/edgedb/bin:/Users/ambv/.dot_files/bin:/Users/ambv/.poetry/bin:/Users/ambv/.cargo/bin:/Users/ambv/.local/bin:/Library/TeX/texbin:/opt/homebrew/bin:/usr/local/opt/autoconf@2.69/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Users/ambv/opt/anaconda3/condabin python3.11 generate-darwin-source-and-headers.py --only-ios 2>&1 | tee -a ../libffi-iOS.config.log
/bin/sh: Support/edgedb/bin:/Users/ambv/.dot_files/bin:/Users/ambv/.poetry/bin:/Users/ambv/.ca …
```

Support PATH variables with spaces

---

Makefile

to make use of `make`'s feature to omit targets representing files that have already been built (in this case downloaded).
To force a rebuild (re-download) use `make`'s `-B` (`--always-make` flag to "[u]nconditionally make all targets."

Improve download related targets

---

Makefile

Thanks for merging PR #155, @freakboy3742, much appreciated.
It seems that PR was missing some changes that slipped my attention and broke the `dev` branch; apologies for that.
This PR adds the missing changes (see commit fac33f9) and corrects (commit 9514d46) and improves (commit 6d1511b) the downloads targets further.
I have tested these changes successfully before issue this PR and I hope you agree with the proposed changes.

Fixup improve download changes

---

README.rst

minor fix to README's links, were formatted as Markdown.

README - fix incorrectly formatted links

---

Makefile

from sourceforge.
I ran into issues with the Makefile when downloads xz, forward to and hosted on sourceforge, as the curl would download a HTML page instead of the source archive.
Adding a wget user-agent fixed the issue for me.

Disable use of .curlrc when downloading sources

---

.github/workflows/release.yaml

- RE: https://github.com/beeware/.github/issues/77
- Bump `upload-artifact` and `download-artifact` actions to v4
- To accommodate v4:
- Artifacts must have unique names since multiple uploads cannot contribute to a single artifact
- Use a wildcard pattern to download all artifacts and merge in to a single directory

Upgrade `upload-artifact` and `download-artifact` actions to v4

---

USAGE.md

Mention in the guide that embedding Python requires disabling dead code removal.
When attempting to embed Python as per `USAGE.md` people end up with non-working solution due to linker removing parts of embedded Python that it found unused. For example, importing `base64` fails due to inability to load `_PyFloat_Pack4`.

Add disabling dead code stripping in linker

---

.github/workflows/ci.yaml

Now that the framework-based support is all in place, we can revert the TODOs that tied the usage of Briefcase to the in-progress branches.
This can't be merged until full binary support is restored to beeware/Python-support-testbed (see beeware/Python-support-testbed#49).
When this PR is merged, we can delete the branches associated with:
* beeware/briefcase-macOS-Xcode-template#47
* beeware/briefcase-macOS-app-template#64
* beeware/briefcase-iOS-Xcode-template#37
* beeware/briefcase#1934

Revert TODOs related to in-progress briefcase work.

---

Makefile
patch/Python/sitecustomize.iOS.py

Pip 24.3 includes explicit support for iOS as a platform; the sitecustomize shim provided by the support package triggers this handling. However, it then requires `platform.ios_ver()` and `sys.implementation._multiarch` to return the correct values to determine the tag name.

Add ios_ver and _multiarch shims for pip 24.3 support.

---

Makefile
USAGE.md
patch/Python/module.modulemap

Fixes #234.
Adds a Swift modulemap to the generated frameworks, and updates the PythonKit usage guide to include the correct details on path information.

Improve support for PythonKit, and update usage guide

---

CONTRIBUTING.md

I had this experience while fixing things, but since this is open source, I realize it'd be beneficial to tell everyone.

Add Python.patch Note to Contributing.md

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
Makefile
patch/Python/Python.patch
patch/Python/release.visionOS.exclude

Refs #269, fixes #207, cross-refs https://github.com/freakboy3742/cpython/pull/6
Old PR but on a different branch than main.
Sorry for the main stuff.

visionOS Support

---

Makefile

However, this does NOT work. Somehow when I unpack the finished support package and find the testbed, this happens:

Fix an iOS reference in testbed cloning.

---

README.rst
USAGE.md

Document support for visionOS and fix some other issues like link formatting
(My own opinion) RST and MD are competing, I think we should make a new format with both the good of RST and MD so we don't have to make choices between them and then get myself confused.

visionOS Support and Other Fixes

---

patch/Python/_cross_target.py.tmpl

Updates the cross-venv script to ensure that the base_prefix is set correctly.
This then flows through to some of the paths in the `venv` scheme; without this patch, the `include` path will point a the location of the macOS interpreter running the cross-venv.

Ensure base_prefix is set in a cross-venv.

---

CONTRIBUTING.md

Update CONTRIBUTING.md for Grammar + Clarity

---

USAGE.md

A lot of the PATHs are redundant in USAGE.md, so this PR removes them.

Remove some useless PATHs in Usage.md

---

Makefile
patch/Python/OpenSSL.xcprivacy

Fixes #268.
Fixes #286 
As of April 2025, Apple has started [flagging certain third-party SDKs as "privacy sensitive"](https://developer.apple.com/support/third-party-SDK-requirements). OpenSSL is one of the affected libraries; this PR adds an `.xcprivacy` file for the two Python modules that link OpenSSL (`_hashlib` and `_ssl`). The Xcode project can then post-process these `.xcprivacy` files into the final Framework.
Also performs post-processing to extract dSYM files into the right location in the built project.
Currently submitted as a draft awaiting confirmation that this actually satisfies Apple's review requirements. An app using these files has passed initial automated validation and reviews.

Add xcprivacy handling for modules that link OpenSSL.

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
README.rst
USAGE.md

Backport of #293 to 3.13 branch.

Disable dSYM production

---

.github/workflows/ci.yaml
patch/Python/Python.patch

Splits the test phase out from the build phase in CI, so that any failure in testing (due to simulator issues) doesn't require a full re-build.
Also adds a minimal usage of the built-in testbed app for iOS and visionOS, to confirm that it works.
Fixes #287
Fixes #288

Separate testing from build; and add testbed testing.

---

.github/workflows/ci.yaml
Makefile
patch/Python/Python.patch

Adds a patch to account for empty testing simulator sets.
Also adds CI to confirm the testbed works in a CI environment.

Correct issues with testing in CI (#295)

---

patch/Python/_cross_target.py.tmpl

Ensure that `sysconfig._BASE_PREFIX` is bound to `base_prefix`, not `prefix`.

Correct handling of sysconfig._BASE_PREFIX in cross environments.

---

patch/Python/_cross_target.py.tmpl

Ensure that sysconfig._BASE_PREFIX is bound to base_prefix, not prefix.

Correct handling of sysconfig._BASE_PREFIX in cross environments. (#297)

---

Makefile
patch/Python/Python.patch

Update patch to Python 3.13.5.

Update patch to Python 3.13.5

---

.github/workflows/ci.yaml
.gitignore
patch/Python/_cross_target.py.tmpl
tests/test_cross_env.py

Correct the sysconfig path definitions in a cross-platform venv. 
Also adds a test to ensure that cross-venv values remain correct in future.

Correct cross-platform venv path handling

---

.github/workflows/ci.yaml
Makefile
patch/Python/Python.patch

Bump 3.14 branch to 3.14.0rc3.

Bump to Python 3.14.0rc3.

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml
Makefile
README.md
USAGE.md
patch/Python/Python.patch

3.13.7 update

---

Makefile
patch/Python/Python.patch

Update patches to support Python 3.13.8.

Update patch to 3.13.8.
